<?php

/*
 * Copyright (C) 2015 WPAdminMate.com (email: info@wpadminmate.com)
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

/**
 * @author JD Tool Kit
 */
class JDTK_Icon_Picker extends JDTK_Type_UI {

  private $iconlist;
  private $iconbrandlist;

  public function init_ui() {
    $this->iconlist = array(
      'initial' => array(
        'title' => __("Rollback to initial icon", 'jdtk'),
        'item' => "dashicons-empty"
      ),
      'empty' => array(
        'title' => __("If you don't want any icon, click here", 'jdtk'),
        'item' => "dashicons-empty"
      ),
      'media' => array(
        'title' => __("Click here to open Media Library", 'jdtk'),
        'item' => __("Open Media Library", 'jdtk')
      ),
      'dashicons-admin-menu' => array(
        'title' => __("Admin Menu", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-menu",
          "dashicons-admin-site",
          "dashicons-dashboard",
          "dashicons-admin-post",
          "dashicons-admin-media",
          "dashicons-admin-links",
          "dashicons-admin-page",
          "dashicons-admin-comments",
          "dashicons-admin-appearance",
          "dashicons-admin-plugins",
          "dashicons-admin-users",
          "dashicons-admin-tools",
          "dashicons-admin-settings",
          "dashicons-admin-network",
          "dashicons-admin-home",
          "dashicons-admin-generic",
          "dashicons-admin-collapse",
        )
      ),
      'dashicons-welcome' => array(
        'title' => __("Welcome Screen", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-welcome-write-blog",
          "dashicons-welcome-add-page",
          "dashicons-welcome-view-site",
          "dashicons-welcome-widgets-menus",
          "dashicons-welcome-comments",
          "dashicons-welcome-learn-more",
        )
      ),
      'dashicons-formats' => array(
        'title' => __("Post Formats", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-format-aside",
          "dashicons-format-image",
          "dashicons-format-gallery",
          "dashicons-format-video",
          "dashicons-format-status",
          "dashicons-format-quote",
          "dashicons-format-chat",
          "dashicons-format-audio",
          "dashicons-camera",
          "dashicons-images-alt",
          "dashicons-images-alt2",
          "dashicons-video-alt",
          "dashicons-video-alt2",
          "dashicons-video-alt3"
        )
      ),
      'dashicons-media' => array(
        'title' => __("Media", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-media-archive",
          "dashicons-media-audio",
          "dashicons-media-code",
          "dashicons-media-default",
          "dashicons-media-document",
          "dashicons-media-interactive",
          "dashicons-media-spreadsheet",
          "dashicons-media-text",
          "dashicons-media-video",
          "dashicons-playlist-audio",
          "dashicons-playlist-video",
          "dashicons-controls-play",
          "dashicons-controls-pause",
          "dashicons-controls-forward",
          "dashicons-controls-skipforward",
          "dashicons-controls-back",
          "dashicons-controls-skipback",
          "dashicons-controls-repeat",
          "dashicons-controls-volumeon",
          "dashicons-controls-volumeoff"
        )
      ),
      'dashicons-image' => array(
        'title' => __("Image Editing", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-image-crop",
          "dashicons-image-rotate-left",
          "dashicons-image-rotate-right",
          "dashicons-image-flip-vertical",
          "dashicons-image-flip-horizontal",
          "dashicons-undo",
          "dashicons-redo"
        )
      ),
      'dashicons-mce' => array(
        'title' => __("TinyMCE", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-editor-bold",
          "dashicons-editor-italic",
          "dashicons-editor-ul",
          "dashicons-editor-ol",
          "dashicons-editor-quote",
          "dashicons-editor-alignleft",
          "dashicons-editor-aligncenter",
          "dashicons-editor-alignright",
          "dashicons-editor-insertmore",
          "dashicons-editor-spellcheck",
          "dashicons-editor-expand",
          "dashicons-editor-contract",
          "dashicons-editor-kitchensink",
          "dashicons-editor-underline",
          "dashicons-editor-justify",
          "dashicons-editor-textcolor",
          "dashicons-editor-paste-word",
          "dashicons-editor-paste-text",
          "dashicons-editor-removeformatting",
          "dashicons-editor-video",
          "dashicons-editor-customchar",
          "dashicons-editor-outdent",
          "dashicons-editor-indent",
          "dashicons-editor-help",
          "dashicons-editor-strikethrough",
          "dashicons-editor-unlink",
          "dashicons-editor-rtl",
          "dashicons-editor-break",
          "dashicons-editor-code",
          "dashicons-editor-paragraph"
        )
      ),
      'dashicons-screen' => array(
        'title' => __("Posts Screen", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-align-left",
          "dashicons-align-right",
          "dashicons-align-center",
          "dashicons-align-none",
          "dashicons-lock",
          "dashicons-calendar",
          "dashicons-calendar-alt",
          "dashicons-visibility",
          "dashicons-post-status",
          "dashicons-edit",
          "dashicons-trash"
        )
      ),
      'dashicons-sorting' => array(
        'title' => __("Sorting", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-external",
          "dashicons-arrow-up",
          "dashicons-arrow-down",
          "dashicons-arrow-right",
          "dashicons-arrow-left",
          "dashicons-arrow-up-alt",
          "dashicons-arrow-down-alt",
          "dashicons-arrow-right-alt",
          "dashicons-arrow-left-alt",
          "dashicons-arrow-up-alt2",
          "dashicons-arrow-down-alt2",
          "dashicons-arrow-right-alt2",
          "dashicons-arrow-left-alt2",
          "dashicons-sort",
          "dashicons-leftright",
          "dashicons-randomize",
          "dashicons-list-view",
          "dashicons-exerpt-view",
          "dashicons-grid-view"
        )
      ),
      'dashicons-social' => array(
        'title' => __("Social", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-share",
          "dashicons-share-alt",
          "dashicons-share-alt2",
          "dashicons-twitter",
          "dashicons-rss",
          "dashicons-email",
          "dashicons-email-alt",
          "dashicons-facebook",
          "dashicons-facebook-alt",
          "dashicons-googleplus",
          "dashicons-networking"
        )
      ),
      'dashicons-specific' => array(
        'title' => __("WordPress.org Specific: Jobs, Profiles, WordCamps", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-hammer",
          "dashicons-art",
          "dashicons-migrate",
          "dashicons-performance",
          "dashicons-universal-access",
          "dashicons-universal-access-alt",
          "dashicons-tickets",
          "dashicons-nametag",
          "dashicons-clipboard",
          "dashicons-heart",
          "dashicons-megaphone",
          "dashicons-schedule"
        )
      ),
      'dashicons-products' => array(
        'title' => __("Products", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-wordpress",
          "dashicons-wordpress-alt",
          "dashicons-pressthis",
          "dashicons-update",
          "dashicons-screenoptions",
          "dashicons-info",
          "dashicons-cart",
          "dashicons-feedback",
          "dashicons-cloud",
          "dashicons-translation"
        )
      ),
      'dashicons-taxonomies' => array(
        'title' => __("Taxonomies", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-tag",
          "dashicons-category"
        )
      ),
      'dashicons-widgets' => array(
        'title' => __("Widgets", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-archive",
          "dashicons-tagcloud",
          "dashicons-text"
        )
      ),
      'dashicons-notifications' => array(
        'title' => __("Notifications", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-yes",
          "dashicons-no",
          "dashicons-no-alt",
          "dashicons-plus",
          "dashicons-plus-alt",
          "dashicons-minus",
          "dashicons-dismiss",
          "dashicons-marker",
          "dashicons-star-filled",
          "dashicons-star-half",
          "dashicons-star-empty",
          "dashicons-flag"
        )
      ),
      'dashicons-misc' => array(
        'title' => __("Misc", 'jdtk'),
        'prefix' => 'dashicons',
        'members' => array(
          "dashicons-location",
          "dashicons-location-alt",
          "dashicons-vault",
          "dashicons-shield",
          "dashicons-shield-alt",
          "dashicons-sos",
          "dashicons-search",
          "dashicons-slides",
          "dashicons-analytics",
          "dashicons-chart-pie",
          "dashicons-chart-bar",
          "dashicons-chart-line",
          "dashicons-chart-area",
          "dashicons-groups",
          "dashicons-businessman",
          "dashicons-id",
          "dashicons-id-alt",
          "dashicons-products",
          "dashicons-awards",
          "dashicons-forms",
          "dashicons-testimonial",
          "dashicons-portfolio",
          "dashicons-book",
          "dashicons-book-alt",
          "dashicons-download",
          "dashicons-upload",
          "dashicons-backup",
          "dashicons-clock",
          "dashicons-lightbulb",
          "dashicons-microphone",
          "dashicons-desktop",
          "dashicons-tablet",
          "dashicons-smartphone",
          "dashicons-phone",
          "dashicons-index-card",
          "dashicons-carrot",
          "dashicons-building",
          "dashicons-store",
          "dashicons-album",
          "dashicons-palmtree",
          "dashicons-tickets-alt",
          "dashicons-money",
          "dashicons-smiley"
        )
      ),
      'jdtk-icon-genericon' => array(
        'title' => __("Genericons", 'jdtk'),
        'prefix' => 'genericon',
        'members' => array(
          "genericon-standard",
          "genericon-aside",
          "genericon-image",
          "genericon-gallery",
          "genericon-video",
          "genericon-status",
          "genericon-quote",
          "genericon-link",
          "genericon-chat",
          "genericon-audio",
          "genericon-github",
          "genericon-dribbble",
          "genericon-twitter",
          "genericon-facebook",
          "genericon-facebook-alt",
          "genericon-wordpress",
          "genericon-googleplus",
          "genericon-linkedin",
          "genericon-linkedin-alt",
          "genericon-pinterest",
          "genericon-pinterest-alt",
          "genericon-flickr",
          "genericon-vimeo",
          "genericon-youtube",
          "genericon-tumblr",
          "genericon-instagram",
          "genericon-codepen",
          "genericon-polldaddy",
          "genericon-googleplus-alt",
          "genericon-path",
          "genericon-skype",
          "genericon-digg",
          "genericon-reddit",
          "genericon-stumbleupon",
          "genericon-pocket",
          "genericon-dropbox",
          "genericon-foursquare",
          "genericon-comment",
          "genericon-category",
          "genericon-tag",
          "genericon-time",
          "genericon-user",
          "genericon-day",
          "genericon-week",
          "genericon-month",
          "genericon-pinned",
          "genericon-search",
          "genericon-unzoom",
          "genericon-zoom",
          "genericon-show",
          "genericon-hide",
          "genericon-close",
          "genericon-close-alt",
          "genericon-trash",
          "genericon-star",
          "genericon-home",
          "genericon-mail",
          "genericon-edit",
          "genericon-reply",
          "genericon-feed",
          "genericon-warning",
          "genericon-share",
          "genericon-attachment",
          "genericon-location",
          "genericon-checkmark",
          "genericon-menu",
          "genericon-refresh",
          "genericon-minimize",
          "genericon-maximize",
          "genericon-404",
          "genericon-spam",
          "genericon-summary",
          "genericon-cloud",
          "genericon-key",
          "genericon-dot",
          "genericon-next",
          "genericon-previous",
          "genericon-expand",
          "genericon-collapse",
          "genericon-dropdown",
          "genericon-dropdown-left",
          "genericon-top",
          "genericon-draggable",
          "genericon-phone",
          "genericon-send-to-phone",
          "genericon-plugin",
          "genericon-cloud-download",
          "genericon-cloud-upload",
          "genericon-external",
          "genericon-document",
          "genericon-book",
          "genericon-cog",
          "genericon-unapprove",
          "genericon-cart",
          "genericon-pause",
          "genericon-stop",
          "genericon-skip-back",
          "genericon-skip-ahead",
          "genericon-play",
          "genericon-tablet",
          "genericon-send-to-tablet",
          "genericon-info",
          "genericon-notice",
          "genericon-help",
          "genericon-fastforward",
          "genericon-rewind",
          "genericon-portfolio",
          "genericon-heart",
          "genericon-code",
          "genericon-subscribe",
          "genericon-unsubscribe",
          "genericon-subscribed",
          "genericon-reply-alt",
          "genericon-reply-single",
          "genericon-flag",
          "genericon-print",
          "genericon-lock",
          "genericon-bold",
          "genericon-italic",
          "genericon-picture",
          "genericon-fullscreen",
          "genericon-website",
          "genericon-ellipsis",
          "genericon-uparrow",
          "genericon-rightarrow",
          "genericon-downarrow",
          "genericon-leftarrow",
          "genericon-xpost",
          "genericon-hierarchy",
          "genericon-paintbrush",
          "genericon-sitemap",
          "genericon-activity",
          "genericon-anchor",
          "genericon-bug",
          "genericon-download",
          "genericon-handset",
          "genericon-microphone",
          "genericon-minus",
          "genericon-move",
          "genericon-plus",
          "genericon-rating-empty",
          "genericon-rating-full",
          "genericon-rating-half",
          "genericon-shuffle",
          "genericon-spotify",
          "genericon-twitch",
          "genericon-videocamera"
        )
      ),
      'jdtk-icon-glyphicon' => array(
        'title' => __("Glyphicon", 'jdtk'),
        'prefix' => 'glyphicon',
        'members' => array(
          "glyphicon-asterisk",
          "glyphicon-plus",
          "glyphicon-euro",
          "glyphicon-eur",
          "glyphicon-minus",
          "glyphicon-cloud",
          "glyphicon-envelope",
          "glyphicon-pencil",
          "glyphicon-glass",
          "glyphicon-music",
          "glyphicon-search",
          "glyphicon-heart",
          "glyphicon-star",
          "glyphicon-star-empty",
          "glyphicon-user",
          "glyphicon-film",
          "glyphicon-th-large",
          "glyphicon-th",
          "glyphicon-th-list",
          "glyphicon-ok",
          "glyphicon-remove",
          "glyphicon-zoom-in",
          "glyphicon-zoom-out",
          "glyphicon-off",
          "glyphicon-signal",
          "glyphicon-cog",
          "glyphicon-trash",
          "glyphicon-home",
          "glyphicon-file",
          "glyphicon-time",
          "glyphicon-road",
          "glyphicon-download-alt",
          "glyphicon-download",
          "glyphicon-upload",
          "glyphicon-inbox",
          "glyphicon-play-circle",
          "glyphicon-repeat",
          "glyphicon-refresh",
          "glyphicon-list-alt",
          "glyphicon-lock",
          "glyphicon-flag",
          "glyphicon-headphones",
          "glyphicon-volume-off",
          "glyphicon-volume-down",
          "glyphicon-volume-up",
          "glyphicon-qrcode",
          "glyphicon-barcode",
          "glyphicon-tag",
          "glyphicon-tags",
          "glyphicon-book",
          "glyphicon-bookmark",
          "glyphicon-print",
          "glyphicon-camera",
          "glyphicon-font",
          "glyphicon-bold",
          "glyphicon-italic",
          "glyphicon-text-height",
          "glyphicon-text-width",
          "glyphicon-align-left",
          "glyphicon-align-center",
          "glyphicon-align-right",
          "glyphicon-align-justify",
          "glyphicon-list",
          "glyphicon-indent-left",
          "glyphicon-indent-right",
          "glyphicon-facetime-video",
          "glyphicon-picture",
          "glyphicon-map-marker",
          "glyphicon-adjust",
          "glyphicon-tint",
          "glyphicon-edit",
          "glyphicon-share",
          "glyphicon-check",
          "glyphicon-move",
          "glyphicon-step-backward",
          "glyphicon-fast-backward",
          "glyphicon-backward",
          "glyphicon-play",
          "glyphicon-pause",
          "glyphicon-stop",
          "glyphicon-forward",
          "glyphicon-fast-forward",
          "glyphicon-step-forward",
          "glyphicon-eject",
          "glyphicon-chevron-left",
          "glyphicon-chevron-right",
          "glyphicon-plus-sign",
          "glyphicon-minus-sign",
          "glyphicon-remove-sign",
          "glyphicon-ok-sign",
          "glyphicon-question-sign",
          "glyphicon-info-sign",
          "glyphicon-screenshot",
          "glyphicon-remove-circle",
          "glyphicon-ok-circle",
          "glyphicon-ban-circle",
          "glyphicon-arrow-left",
          "glyphicon-arrow-right",
          "glyphicon-arrow-up",
          "glyphicon-arrow-down",
          "glyphicon-share-alt",
          "glyphicon-resize-full",
          "glyphicon-resize-small",
          "glyphicon-exclamation-sign",
          "glyphicon-gift",
          "glyphicon-leaf",
          "glyphicon-fire",
          "glyphicon-eye-open",
          "glyphicon-eye-close",
          "glyphicon-warning-sign",
          "glyphicon-plane",
          "glyphicon-calendar",
          "glyphicon-random",
          "glyphicon-comment",
          "glyphicon-magnet",
          "glyphicon-chevron-up",
          "glyphicon-chevron-down",
          "glyphicon-retweet",
          "glyphicon-shopping-cart",
          "glyphicon-folder-close",
          "glyphicon-folder-open",
          "glyphicon-resize-vertical",
          "glyphicon-resize-horizontal",
          "glyphicon-hdd",
          "glyphicon-bullhorn",
          "glyphicon-bell",
          "glyphicon-certificate",
          "glyphicon-thumbs-up",
          "glyphicon-thumbs-down",
          "glyphicon-hand-right",
          "glyphicon-hand-left",
          "glyphicon-hand-up",
          "glyphicon-hand-down",
          "glyphicon-circle-arrow-right",
          "glyphicon-circle-arrow-left",
          "glyphicon-circle-arrow-up",
          "glyphicon-circle-arrow-down",
          "glyphicon-globe",
          "glyphicon-wrench",
          "glyphicon-tasks",
          "glyphicon-filter",
          "glyphicon-briefcase",
          "glyphicon-fullscreen",
          "glyphicon-dashboard",
          "glyphicon-paperclip",
          "glyphicon-heart-empty",
          "glyphicon-link",
          "glyphicon-phone",
          "glyphicon-pushpin",
          "glyphicon-usd",
          "glyphicon-gbp",
          "glyphicon-sort",
          "glyphicon-sort-by-alphabet",
          "glyphicon-sort-by-alphabet-alt",
          "glyphicon-sort-by-order",
          "glyphicon-sort-by-order-alt",
          "glyphicon-sort-by-attributes",
          "glyphicon-sort-by-attributes-alt",
          "glyphicon-unchecked",
          "glyphicon-expand",
          "glyphicon-collapse-down",
          "glyphicon-collapse-up",
          "glyphicon-log-in",
          "glyphicon-flash",
          "glyphicon-log-out",
          "glyphicon-new-window",
          "glyphicon-record",
          "glyphicon-save",
          "glyphicon-open",
          "glyphicon-saved",
          "glyphicon-import",
          "glyphicon-export",
          "glyphicon-send",
          "glyphicon-floppy-disk",
          "glyphicon-floppy-saved",
          "glyphicon-floppy-remove",
          "glyphicon-floppy-save",
          "glyphicon-floppy-open",
          "glyphicon-credit-card",
          "glyphicon-transfer",
          "glyphicon-cutlery",
          "glyphicon-header",
          "glyphicon-compressed",
          "glyphicon-earphone",
          "glyphicon-phone-alt",
          "glyphicon-tower",
          "glyphicon-stats",
          "glyphicon-sd-video",
          "glyphicon-hd-video",
          "glyphicon-subtitles",
          "glyphicon-sound-stereo",
          "glyphicon-sound-dolby",
          "glyphicon-sound-5-1",
          "glyphicon-sound-6-1",
          "glyphicon-sound-7-1",
          "glyphicon-copyright-mark",
          "glyphicon-registration-mark",
          "glyphicon-cloud-download",
          "glyphicon-cloud-upload",
          "glyphicon-tree-conifer",
          "glyphicon-tree-deciduous",
          "glyphicon-cd",
          "glyphicon-save-file",
          "glyphicon-open-file",
          "glyphicon-level-up",
          "glyphicon-copy",
          "glyphicon-paste",
          "glyphicon-alert",
          "glyphicon-equalizer",
          "glyphicon-king",
          "glyphicon-queen",
          "glyphicon-pawn",
          "glyphicon-bishop",
          "glyphicon-knight",
          "glyphicon-baby-formula",
          "glyphicon-tent",
          "glyphicon-blackboard",
          "glyphicon-bed",
          "glyphicon-apple",
          "glyphicon-erase",
          "glyphicon-hourglass",
          "glyphicon-lamp",
          "glyphicon-duplicate",
          "glyphicon-piggy-bank",
          "glyphicon-scissors",
          "glyphicon-bitcoin",
          "glyphicon-btc",
          "glyphicon-xbt",
          "glyphicon-yen",
          "glyphicon-jpy",
          "glyphicon-ruble",
          "glyphicon-rub",
          "glyphicon-scale",
          "glyphicon-ice-lolly",
          "glyphicon-ice-lolly-tasted",
          "glyphicon-education",
          "glyphicon-option-horizontal",
          "glyphicon-option-vertical",
          "glyphicon-menu-hamburger",
          "glyphicon-modal-window",
          "glyphicon-oil",
          "glyphicon-grain",
          "glyphicon-sunglasses",
          "glyphicon-text-size",
          "glyphicon-text-color",
          "glyphicon-text-background",
          "glyphicon-object-align-top",
          "glyphicon-object-align-bottom",
          "glyphicon-object-align-horizontal",
          "glyphicon-object-align-left",
          "glyphicon-object-align-vertical",
          "glyphicon-object-align-right",
          "glyphicon-triangle-right",
          "glyphicon-triangle-left",
          "glyphicon-triangle-bottom",
          "glyphicon-triangle-top",
          "glyphicon-console",
          "glyphicon-superscript",
          "glyphicon-subscript",
          "glyphicon-menu-left",
          "glyphicon-menu-right",
          "glyphicon-menu-down",
          "glyphicon-menu-up"
        )
      )
    );

    $this->iconbrandlist = array('dashicons', 'genericon', 'glyphicon');

    $html_str = "<div id='iconpicker' title='" . __("Please choose an icon you like", 'jdtk') . "'>"
      . "<ul id='icons'>";

    foreach ($this->iconlist as $section_id => $section) {
      $html_str .= "<div class='$section_id'>";
      $html_str .= "<h4>" . $section['title'] . "</h4>";
      switch ($section_id) {
        case 'initial':
          $html_str .="<li class='jdtk-icon-item icon'><span></span></li>";
          break;
        case 'empty':
          $html_str .="<li class='jdtk-icon-item icon' title='"
            . $section['item'] . "'><span class='dashicons "
            . $section['item'] . "'></span></li>";
          break;
        case 'media':
          $html_str .= "<li class='jdtk-icon-item media'><span class='text'>"
            . $section['item'] . "</span></li>";
          break;
        default:
          foreach ($section['members'] as $key => $icon) {
            $html_str .= "<li class='jdtk-icon-item icon' title='$icon'>"
              . "<span class='" . $section['prefix'] . " $icon'></span></li>";
          }
      }
      $html_str .= "<br><hr></div>";
    }

    $html_str .= "</ul></div>"
      . "<div id='icon-too-big' class='jdtk-dialog' "
      . "title='" . __("Warning: Trying to use an oversize icon", 'jdtk') . "'>"
      . "<p>" . __("The icon that you chose is too large. "
        . "Please choose again an icon with its dimension not larger than 36 x 36 pixels."
        . "Recommand dimension is 24 x 24 pixels.", 'jdtk') . "</p>"
      . "</div>";

    echo $html_str;

    foreach (array('genericon genericon-standard', 'glyphicon glyphicon-asterisk') as $icon) {
      echo "<div class='jdtk_hidden_icon'><span class='$icon'></span></div>";
    }
  }

  public function add_actions() {
    
  }

}
